### ISSUE TITLE
`~/.local/share` location doesn't work

### ISSUE THREAD

**Issue by RundownRhino** [BanchouBoo/mpv-youtube-chat#5]
If `XDG_DATA_HOME` isn't set, making the script fall back to `~/.local/share`, then the script never finds the files it downloads - `file_exists` returns false, even though the chat file is there.

After debugging it in various ways, I think the culprit is that Lua's `io.open` doesn't expand `~` in paths. Changing the fallback value of `xdg_data_home` from `"~/.local/share"` to `os.getenv("HOME") .. "/.local/share"` fixed the issue for me.

**Comment by BanchouBoo** [comment]
Fixed
