### ISSUE TITLE
api bad request 

### ISSUE THREAD

**Issue by Theo1996** [BanchouBoo/mpv-youtube-chat#6]
`[mpv_youtube_chat_master] Lua error: ...portable_config/scripts/mpv-youtube-chat-master/main.lua:9: attempt to concatenate a nil value`
changedthe second "home" to "userprofile" in line 9, since windows doesnt have "home"
it started working but then:

> [mpv_youtube_chat_master] WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
> AV: 00:00:06 / 05:23:22 (0%) A-V:  0.000 Cache: 200s/14MB
> [mpv_youtube_chat_master] [youtube] EOkuS_mgr3s: Downloading android player API JSON
> [mpv_youtube_chat_master] WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (1/3)...
> AV: 00:00:07 / 05:23:22 (0%) A-V:  0.000 Cache: 217s/16MB
> [mpv_youtube_chat_master] WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
> [mpv_youtube_chat_master] [youtube] EOkuS_mgr3s: Downloading android player API JSON
> [mpv_youtube_chat_master] WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (2/3)...
> AV: 00:00:07 / 05:23:22 (0%) A-V:  0.000 Cache: 222s/16MB
> [mpv_youtube_chat_master] WARNING: [youtube] YouTube said: ERROR - Precondition check failed.
> [mpv_youtube_chat_master] [youtube] EOkuS_mgr3s: Downloading android player API JSON
> [mpv_youtube_chat_master] WARNING: [youtube] HTTP Error 400: Bad Request. Retrying (3/3)...

win 7 64 bit ultimate
mpv version 2023.12.30

**Comment by BanchouBoo** [comment]
> `[mpv_youtube_chat_master] Lua error: ...portable_config/scripts/mpv-youtube-chat-master/main.lua:9: attempt to concatenate a nil value`

Fixed in https://github.com/BanchouBoo/mpv-youtube-chat/commit/ffa1161fbd1b664cd7e8a9fb8ffae9a33db5ebe8

The rest of the errors are problems with yt-dlp so I can't really help there. Make sure you're up to date, and make sure mpv is configured to point to it correctly.

**Comment by Theo1996** [comment]
Downloaded the new version it still says bad API etc like I mentioned above but then it downloads the chat normally and it displays it in the video thank you! 
Does it delete the chat logs after? Or do I have to do that manually?

**Comment by BanchouBoo** [comment]
You have to delete them manually.
