### ISSUE TITLE
Live chat messages don't break for one word string

### ISSUE THREAD

**Issue by brainwo** [BanchouBoo/mpv-youtube-chat#7]
- Some languages like Chinese and Thai don't use spaces.
- Sometimes people love to send random gibberish spam chat.
- There are also chat that contains emoji only (which is not being parsed by this plugin, resulting in the screen filled up with: `:yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis::yougotthis:`

**Comment by BanchouBoo** [comment]
Fixed in https://github.com/BanchouBoo/mpv-youtube-chat/commit/4b8d6d5d3ace40d467bc0ed75f3af2a1aefce161, there is now a `message-break-anywhere` option as well as a `break-anywhere` action to toggle/set the value from a keybind or the console.

**Comment by brainwo** [comment]
Wow, thank you for your prompt response, highly appreciated that :+1:
